name       : pandoc
version    : '2.5'
release    : 4
source     :
    - https://hackage.haskell.org/package/pandoc-2.5/pandoc-2.5.tar.gz : d57dc5db78a0a304de70436fe59a7599ab0c6d0fb2ab6704eeae498a4536222e
license    : BSD-3-Clause
component  : office
summary    : Pandoc is a Haskell library for converting from one markup format to another, and a command-line tool that uses this library
description: |
    Pandoc is a Haskell library for converting from one markup format to another, and a command-line tool that uses this library
builddeps  :
    - haskell-aeson-pretty-devel
    - haskell-cabal-install
    - haskell-cmark-gfm-devel
    - haskell-doctemplates-devel
    - haskell-glob-devel
    - haskell-haddock-library-devel
    - haskell-hslua-module-text-devel
    - haskell-HTTP-devel
    - haskell-http-client-tls-devel
    - haskell-JuicyPixels-devel
    - haskell-sha-devel
    - haskell-skylighting-devel
    - haskell-split-devel
    - haskell-tagsoup-devel
    - haskell-temporary-devel
    - haskell-texmath-devel
    - haskell-unicode-transforms-devel
    - haskell-zip-archive-devel
rundeps    :
    - devel:
        - haskell-aeson-pretty-devel
        - haskell-cmark-gfm-devel
        - haskell-doctemplates-devel
        - haskell-glob-devel
        - haskell-haddock-library-devel
        - haskell-hslua-module-text-devel
        - haskell-HTTP-devel
        - haskell-http-client-tls-devel
        - haskell-JuicyPixels-devel
        - haskell-sha-devel
        - haskell-skylighting-devel
        - haskell-split-devel
        - haskell-tagsoup-devel
        - haskell-temporary-devel
        - haskell-texmath-devel
        - haskell-unicode-transforms-devel
        - haskell-zip-archive-devel
networking : yes
setup      : |
    %patch -p1 < $pkgfiles/everything_is_old.patch
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
