name       : pandoc
version    : 2.2.1
release    : 3
source     :
    - http://hackage.haskell.org/package/pandoc-2.2.1/pandoc-2.2.1.tar.gz : fe037f5fbb62fb27e7b1dbddfbd0aa45ea6e9fcdaff1f2203f7484c245b211b7
license    : BSD-3-Clause
component  : office
summary    : Pandoc is a Haskell library for converting from one markup format to another, and a command-line tool that uses this library
description: |
    Pandoc is a Haskell library for converting from one markup format to another, and a command-line tool that uses this library
builddeps  :
    - ghc-devel
    - haskell-HTTP
    - haskell-JuicyPixels
    - haskell-aeson-pretty
    - haskell-blaze-html
    - haskell-cabal-install
    - haskell-cmark-gfm
    - haskell-data-default
    - haskell-doctemplates
    - haskell-glob
    - haskell-haddock-library
    - haskell-hslua
    - haskell-hslua-module-text
    - haskell-http-client-tls
    - haskell-pandoc-types
    - haskell-sha
    - haskell-skylighting
    - haskell-split
    - haskell-tagsoup
    - haskell-temporary
    - haskell-texmath
    - haskell-yaml
    - haskell-zip-archive
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
