name       : pandoc
version    : 1.19.2.1
release    : 1
source     :
    - https://hackage.haskell.org/package/pandoc-1.19.2.1/pandoc-1.19.2.1.tar.gz : 08692f3d77bf95bb9ba3407f7af26de7c23134e7efcdafad0bdaf9050e2c7801
license    : BSD-3-Clause
component  : office
summary    : Pandoc is a Haskell library for converting from one markup format to another, and a command-line tool that uses this library
description: |
    Pandoc is a Haskell library for converting from one markup format to another, and a command-line tool that uses this library
builddeps  :
    - ghc-devel
    - haskell-cabal-install
    - haskell-cmark
    - haskell-data-default
    - haskell-doctemplates
    - haskell-extensible-exceptions
    - haskell-filemanip
    - haskell-haddock-library
    - haskell-hslua
    - haskell-JuicyPixels
    - haskell-old-time
    - haskell-sha
    - haskell-skylighting
    - haskell-syb
    - haskell-tagsoup
    - haskell-temporary
    - haskell-texmath
    - haskell-yaml
    - haskell-zip-archive
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
